execute pathogen#infect()

call plug#begin('~/.vim/plugins')

Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'

call plug#end()

" set up editor look
set number
syntax on
colorscheme Tomorrow

" set up tabs
set softtabstop=0
set tabstop=4
set shiftwidth=4
set smarttab
set autoindent
set smartindent
set nowrap
set expandtab
set relativenumber
set noswapfile

" Key Mappings
map <C-n> :NERDTreeToggle<CR>
map <C-s> :w<CR>
map <C-p> :FZF<CR>
map <C-s> :w<CR>
imap <C-s> :w<CR>

" Normal Map
nmap 0 ^

" Command Aliases
command! Reload so %MYVIMRC

" Functions

" Leader Keys
let mapleader = "\<Space>"
nnoremap <Leader>h gT
nnoremap <Leader>l gt
nnoremap <Leader>H :tabm -1<CR>
nnoremap <Leader>L :tabm +1<CR>
nnoremap <Leader>w :close<CR>
